@extends('layouts.admin')

@section('page-title', $procurementNotice->exists ? 'Edit Procurement Notice' : 'Create Procurement Notice')
@section('title', $procurementNotice->exists ? 'Edit Procurement Notice' : 'Create Procurement Notice')

@section('content')
<div class="page-header"><h1>{{ $procurementNotice->exists ? __('Edit Procurement Notice') : __('Create Procurement Notice') }}</h1></div>
<div class="card"><div class="card-body"><form action="{{ $procurementNotice->exists ? route('admin.procurement-notices.update', $procurementNotice) : route('admin.procurement-notices.store') }}" method="POST">@csrf @if($procurementNotice->exists) @method('PUT') @endif
<div class="row">@foreach(['fr' => 'French', 'en' => 'English', 'ar' => 'Arabic'] as $locale => $label)<div class="col-md-4 mb-3"><label class="form-label">{{ __('Title') }} ({{ $label }}) *</label><input class="form-control" name="title_{{ $locale }}" value="{{ old('title_'.$locale, $procurementNotice->{'title_'.$locale} ?? '') }}" required>@error('title_'.$locale)<div class="text-danger">{{ $message }}</div>@enderror</div>@endforeach</div>
<div class="row">@foreach(['fr' => 'French', 'en' => 'English', 'ar' => 'Arabic'] as $locale => $label)<div class="col-md-4 mb-3"><label class="form-label">{{ __('Description') }} ({{ $label }}) *</label><textarea class="form-control" name="description_{{ $locale }}" rows="4" required>{{ old('description_'.$locale, $procurementNotice->{'description_'.$locale} ?? '') }}</textarea>@error('description_'.$locale)<div class="text-danger">{{ $message }}</div>@enderror</div>@endforeach</div>
<div class="row"><div class="col-md-4 mb-3"><label class="form-label">{{ __('Type') }} *</label><select class="form-select" name="type" required>@foreach(['pam' => 'PAM', 'appel_offres' => 'Appel d’offres', 'resultat_designation' => 'Résultat de désignation'] as $value => $label)<option value="{{ $value }}" @selected(old('type', $procurementNotice->type) === $value)>{{ $label }}</option>@endforeach</select></div><div class="col-md-4 mb-3"><label class="form-label">{{ __('Reference Number') }}</label><input class="form-control" name="reference_number" value="{{ old('reference_number', $procurementNotice->reference_number) }}"></div><div class="col-md-4 mb-3"><label class="form-label">{{ __('Attachment Path') }}</label><input class="form-control" name="attachment_path" value="{{ old('attachment_path', $procurementNotice->attachment_path) }}"></div></div>
<div class="row"><div class="col-md-4 mb-3"><label class="form-label">{{ __('Publication Date') }} *</label><input type="date" class="form-control" name="publication_date" value="{{ old('publication_date', optional($procurementNotice->publication_date)->format('Y-m-d')) }}" required></div><div class="col-md-4 mb-3"><label class="form-label">{{ __('Deadline Date') }}</label><input type="date" class="form-control" name="deadline_date" value="{{ old('deadline_date', optional($procurementNotice->deadline_date)->format('Y-m-d')) }}"></div><div class="col-md-2 mb-3"><label class="form-label">{{ __('Order') }}</label><input type="number" class="form-control" name="order" value="{{ old('order', $procurementNotice->order ?? 0) }}"></div><div class="col-md-2 mb-3"><label class="form-label">{{ __('Active') }}</label><select class="form-select" name="is_active"><option value="1" @selected(old('is_active', $procurementNotice->is_active ?? true))>{{ __('Yes') }}</option><option value="0" @selected(!old('is_active', $procurementNotice->is_active ?? true))>{{ __('No') }}</option></select></div></div>
<button class="btn btn-primary">{{ __('Save') }}</button> <a href="{{ route('admin.procurement-notices.index') }}" class="btn btn-secondary">{{ __('Cancel') }}</a></form></div></div>
@endsection
