@extends('layouts.admin')

@section('page-title', $downloadableForm->exists ? __('messages.edit_downloadable_form') : __('messages.new_downloadable_form'))
@section('title', $downloadableForm->exists ? __('messages.edit_downloadable_form') : __('messages.new_downloadable_form'))

@section('content')
<div class="page-header"><h1>{{ $downloadableForm->exists ? __('messages.edit_downloadable_form') : __('messages.new_downloadable_form') }}</h1></div><div class="card"><div class="card-body"><form action="{{ $downloadableForm->exists ? route('admin.downloadable-forms.update', $downloadableForm) : route('admin.downloadable-forms.store') }}" method="POST" enctype="multipart/form-data">@csrf @if($downloadableForm->exists) @method('PUT') @endif
<div class="row">@foreach(['fr' => 'French', 'en' => 'English', 'ar' => 'Arabic'] as $locale => $label)<div class="col-md-4 mb-3"><label class="form-label">{{ __('messages.name') }} ({{ $label }}) *</label><input class="form-control" name="title_{{ $locale }}" value="{{ old('title_'.$locale, $downloadableForm->{'title_'.$locale} ?? '') }}" required></div>@endforeach</div><div class="row">@foreach(['fr' => 'French', 'en' => 'English', 'ar' => 'Arabic'] as $locale => $label)<div class="col-md-4 mb-3"><label class="form-label">{{ __('messages.description') }} ({{ $label }})</label><textarea class="form-control" name="description_{{ $locale }}" rows="3">{{ old('description_'.$locale, $downloadableForm->{'description_'.$locale} ?? '') }}</textarea></div>@endforeach</div><div class="row"><div class="col-md-8 mb-3"><label class="form-label">{{ __('messages.file') }} {{ $downloadableForm->exists ? '' : '*' }}</label><input type="file" class="form-control" name="file" {{ $downloadableForm->exists ? '' : 'required' }}></div><div class="col-md-2 mb-3"><label class="form-label">{{ __('messages.order') }}</label><input type="number" class="form-control" name="order" value="{{ old('order', $downloadableForm->order ?? 0) }}"></div><div class="col-md-2 mb-3"><label class="form-label">{{ __('messages.active') }}</label><select class="form-select" name="is_active"><option value="1" @selected(old('is_active', $downloadableForm->is_active ?? true))>{{ __('messages.yes') }}</option><option value="0" @selected(!old('is_active', $downloadableForm->is_active ?? true))>{{ __('messages.no') }}</option></select></div></div>@if($downloadableForm->file_path)<p class="text-muted">{{ __('messages.current_file') }}: {{ basename($downloadableForm->file_path) }}</p>@endif<button class="btn btn-primary">{{ __('messages.Save') }}</button> <a href="{{ route('admin.downloadable-forms.index') }}" class="btn btn-secondary">{{ __('messages.Cancel') }}</a></form></div></div>
@endsection
