@extends('layouts.admin')

@section('page-title', $establishment->exists ? __('messages.edit_establishment') : __('messages.new_establishment'))
@section('title', $establishment->exists ? __('messages.edit_establishment') : __('messages.new_establishment'))

@section('content')
<div class="page-header"><h1>{{ $establishment->exists ? __('messages.edit_establishment') : __('messages.new_establishment') }}</h1></div><div class="card"><div class="card-body"><form action="{{ $establishment->exists ? route('admin.establishments.update', $establishment) : route('admin.establishments.store') }}" method="POST">@csrf @if($establishment->exists) @method('PUT') @endif
<div class="row">@foreach(['fr' => 'French', 'en' => 'English', 'ar' => 'Arabic'] as $locale => $label)<div class="col-md-4 mb-3"><label class="form-label">{{ __('messages.name') }} ({{ $label }}) *</label><input class="form-control" name="name_{{ $locale }}" value="{{ old('name_'.$locale, $establishment->{'name_'.$locale} ?? '') }}" required></div>@endforeach</div><div class="row"><div class="col-md-4 mb-3"><label class="form-label">{{ __('messages.type') }}</label><input class="form-control" name="type" value="{{ old('type', $establishment->type) }}"></div><div class="col-md-4 mb-3"><label class="form-label">{{ __('messages.phone') }}</label><input class="form-control" name="phone" value="{{ old('phone', $establishment->phone) }}"></div><div class="col-md-2 mb-3"><label class="form-label">{{ __('messages.order') }}</label><input type="number" class="form-control" name="order" value="{{ old('order', $establishment->order ?? 0) }}"></div><div class="col-md-2 mb-3"><label class="form-label">{{ __('messages.active') }}</label><select class="form-select" name="is_active"><option value="1" @selected(old('is_active', $establishment->is_active ?? true))>{{ __('messages.yes') }}</option><option value="0" @selected(!old('is_active', $establishment->is_active ?? true))>{{ __('messages.no') }}</option></select></div></div><div class="mb-3"><label class="form-label">{{ __('messages.address') }}</label><textarea class="form-control" name="address" rows="3">{{ old('address', $establishment->address) }}</textarea></div><button class="btn btn-primary">{{ __('messages.Save') }}</button> <a href="{{ route('admin.establishments.index') }}" class="btn btn-secondary">{{ __('messages.Cancel') }}</a></form></div></div>
@endsection
